- hosts: tag_Name_MONGO
  tasks:
  - name: Configuring the yum repository
    yum_repository:
      name: MongoDB
      baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.4/x86_64/
      description: MongoDB Repository
      gpgcheck: true 
      enabled: true
      gpgkey: https://www.mongodb.org/static/pgp/server-4.4.asc


  - name: Install mongodb
    yum:
      name: mongodb-org
      state: present 

  - name: Configuring mongod to bind to 0.0.0.0 
    replace:
      path: /etc/mongod.conf 
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
    notify: Restart mongod 


  - name: Start the mongod service 
    service:
      name: mongod
      state: started 
      enabled: true 

  handlers:
  - name: Restart mongod 
    service:
      name: mongod
      state: restarted 

